project_id = "wwlsizyhryhiskrzizvw"

[functions.create-users]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
